GUCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/likes-async/', views.likes_async, name='likes-async'),

    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/update/', views.comment_update, name='comment_update'),
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/comments/<int:id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<int:post_id>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/delete/', views.reply_delete, name='reply_delete'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/update/', views.reply_update, name='reply_update'),

    path('catemp/', views.catemp, name='catempPage'),
    path('catemp/create', views.Create_catemp, name='catempCreate'),
    path('catemp/update', views.Update_catemp, name='catempUpdate'),
    path('catemp/delete', views.Delete_catemp, name='catempDelete'),

    path('<str:username>/followsHome/', views.followsHome, name='followsHome'),
    path('<int:id>/<str:username>/followsDetail/', views.followsDetail, name='followsDetail'),

]

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)

class Post(models.Model):

    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default='1')
    TAG_CHOICES = [
        ('RESTAURANT', '맛집'),
        ('HOBBY', '취미'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = ResizedImageField(
        size = [500, 500],
        crop = ['middle', 'center'],
        upload_to = 'image/%Y/%m',
    )
    tag = models.CharField(max_length=30, choices = TAG_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Reply(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post', 'user', 'like_users', )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': '3',
                    'placeholder': '댓글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ('user', 'post', 'comment',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control mt-2',
                    'rows': '3',
                    'placeholder': '답글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }
        

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from accounts.models import User
from .forms import PostForm, CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts': posts,
    }

    return render(request, 'blogHome/base.html', context)

def detail(request, id):
    post = Post.objects.get(id=id)
    sorted_posts = post.user.post_set.all().order_by('-created_at')
    comment_form = CommentForm()
    reply_form = ReplyForm()
    categories = Category.objects.all()

    context = {
        'post':post,
        'sorted_posts':sorted_posts,
        'comment_form':comment_form,
        'reply_form':reply_form,
        'categories':categories,
    }
    return render(request, 'blogDetail/base.html', context)

def catemp(request):
    categories = Category.objects.all()
    if not categories:
        categories = Category()
        categories.category_name = '기본 카테고리'
        categories.save()

    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catemp.html', context)

@login_required
def Create_catemp(request):
    category_name = request.POST['categoryName']
    new_category = Category(category_name = category_name)
    new_category.save()

    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def Update_catemp(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catempUpdate.html', context)

@login_required
def Delete_catemp(request):
    category_id = request.POST['categoryId']
    delete_category = Category.objects.get(id = category_id)
    delete_category.delete()
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    else:
        form = PostForm()
        
    context = {
        'form': form, 
        'categories':categories,
    }

    return render(request, 'form.html', context)


@login_required
def delete(request, id):
    post = Post.objects.get(id=id)
    if request.user == post.user:
        post.delete()

    return redirect('posts:home')


@login_required
def update(request, id):
    post = Post.objects.get(id=id)

    if request.user != post.user:
        return redirect('posts:detail')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', id=post.id)
    
    else:
        form = PostForm(instance=post)

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    
    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()

    return JsonResponse({
                            'id': comment.id,
                            'postId': post_id,
                            'username': comment.user.username,
                            'content': comment.content,
    })


@login_required
def comment_update(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    if request.method == 'POST':
        comment.content = request.POST.get('comment_content')
        comment.save()
        data = {
        'comment_id': id,
        'post_id': post_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    else:
        comment.delete()
        data = {
            'post_id': post_id,
            'comment_id' : id,
        }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')



@login_required
def likes_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False

    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all()),
    }

    return JsonResponse(context)



@login_required
def comment_likes_async(request, post_id, id):
    user = request.user
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=id)

    if user in comment.like_users.all():
        comment.like_users.remove(user)
        status = False

    else:
        comment.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(comment.like_users.all()),
        'post_id': post.id,
        'comment_id': comment.id,
    }
    return JsonResponse(context)


@login_required
def reply_create(request, post_id, comment_id):
    reply_form = ReplyForm(request.POST)
    if reply_form.is_valid():
        reply = reply_form.save(commit=False)
        reply.post_id = post_id
        reply.user = request.user
        reply.comment_id = comment_id
        reply.save() 

    return JsonResponse({
                            'id': reply.id,
                            'postId': post_id,
                            'commentId': comment_id,
                            'username': reply.user.username,
                            'content': reply.content,
    })


@login_required
def reply_delete(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')
    
    else:
        reply.delete()
        data = {
            'reply_id': id,
            'post_id': post_id,
            'comment_id' : comment_id,
        }
    
    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def reply_update(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')

    if request.method == 'POST':
        reply.content = request.POST.get('reply_content')
        reply.save()
        data = {
        'reply_id': id,
        'post_id': post_id,
        'comment_id' : comment_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def followsHome(request, username):
    me = request.user
    you = User.objects.get(username=username)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)
    
    return redirect('posts:home')


@login_required
def followsDetail(request, username, id):
    me = request.user
    you = User.objects.get(username=username)
    post = Post.objects.get(id=id)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)

    context = {
        'post': post,
    }

    return redirect('posts:detail', id=post.id)

posts/templates/_card(old).html
{% load bootstrap5 %}

<div class="row">
    {% for post in posts %}
        {% include '_card.html' %}
    {% endfor %}
</div>



<div class="card my-3 col-12 col-md-5 mx-2">
    
    <div style="display: flex; flex-direction: row; justify-content: space-between;" class="card-header">
        <div>
            {% if post.user.profile_image %}
            <img src="{{ post.user.profile_image.url }}" alt="" class="rounded-circle" width="30px">
            {% else %}
            <img src="/media/profile/default.jpeg" alt="" class="rounded-circle" width="30px">
            {% endif %}
            
            <a href="{% url 'accounts:profile' username=post.user %}" class="text-reset text-decoration-none">{{ post.user }}</a>
        </div>
            
        {% if user == post.user %}
        <div>
            <div>
                <a href="{% url 'posts:update' id=post.id %}">Update</a>
                <a href="{% url 'posts:delete' id=post.id %}">Delete</a>
            </div>
        </div>
        {% endif %}
    </div>

    <img src="{{ post.image.url }}" alt="">

    <div class="card-body">
        {% if user in post.like_users.all %}
            <i class="bi bi-heart-fill heart" style="color:red" data-post-id="{{ post.id }}">{{ post.like_users.all|length }}</i>
        {% else %}
            <i class="bi bi-heart heart" data-post-id="{{ post.id }}">{{ post.like_users.all|length }}</i>
        {% endif %}
        명이 좋아합니다.
        <p class="cart-text">{{ post.title }}</p>
        <p class="cart-text">{{ post.content }}</p>
        <p class="cart-text">{{ post.updated_at }}</p>
        {% if post.comment_set.all|length == 0 %}
        <hr>
        <p>댓글이 없습니다.</p>
        {% endif %}
    </div>

    <hr>

    <ul id="comment-list-{{ post.id }}">
    {% for comment in post.comment_set.all %}
        <div style="margin-bottom: 3px; background-color: rgb(247, 247, 247);">
            <div style="margin-bottom: 3px;">{{ comment.user }} : {{ comment.content }}</div>
            <div style="margin-bottom: 3px;">{{ comment.updated_at }}</div>
            <div class="card-body" style="margin-left: auto;">
                {% if user in comment.like_users.all %}
                <i class="bi bi-heart-fill comment_heart" style="color:red" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" onclick="comment_likeRequest(this, '{{ post.id }}', '{{ comment.id }}')">{{ comment.like_users.all|length }}명이 좋아합니다.</i> 
                {% else %}
                <i class="bi bi-heart comment_heart" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" onclick="comment_likeRequest(this, '{{ post.id }}', '{{ comment.id }}')">{{ comment.like_users.all|length }}명이 좋아합니다.</i>                
                {% endif %}
                
                {% if user == comment.user %}   
                    <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#commentModal{{ post.id }}-{{ comment.id }}">Update</button>
                        {% include '_commentmodal.html' %}
                    <button style="text-align: right;" class="btn btn-light" onclick="commentDelete('{{post.id}},{{comment.id}}');">Delete</button>
                {% endif %}
            </div> 
          
            <ul id="reply-list-{{ post.id }}-{{ comment.id }}">
                <style>div.in {text-indent: 5px;}</style>
            {% for reply in comment.reply_set.all %}
                    <div class="in">{{ reply.user }} : {{ reply.content }} {{ reply.updated_at }}
                {% if user == reply.user %}
                    <button type="button" data-bs-toggle="modal" data-bs-target="#replyModal{{ post.id }}-{{ comment.id }}-{{ reply.id }}">Update</button>
                        {% include '_replymodal.html' %}
                    <button onclick="replyDelete('{{post.id}},{{comment.id}},{{reply.id}}');">Delete</button>
                {% endif %}
                    </div>
            {% endfor %}
            </ul>

            <p class="replybutton">답글 달기</p>
            <div class="replyform_div" style="display: none;">
                {% if user.is_authenticated %}
                <form action="{% url 'posts:reply_create' post_id=post.id comment_id=comment.id %}" method="POST" class="reply-Form">
                    {% csrf_token %}
                    {{ reply_form }}
                    <input type="submit">
                </form>
                {% endif %} 
            </div>
        </div>
    {% endfor %}
    </ul>


    {% if user.is_authenticated %}
    <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST" class="comment-Form">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="Submit">
    </form>
    {% endif %}
    
    <hr>

</div>









    <!-- post like -->
    <script>
        let likeButtons = document.querySelectorAll("i.heart")

        likeButtons.forEach((likeButton)=>{            
            likeButton.addEventListener("click", (event)=>{
                let postId = event.target.dataset.postId 
                likeRequest(event.target, postId)
            })
        })

        let likeRequest = async (button, postId) => {
            let likeURL = `/posts/${postId}/likes-async/`
            let response = await fetch(likeURL)
            let result = await response.json()

            if (result.status) {
                button.classList.remove('bi-heart')
                button.classList.add('bi-heart-fill')
                button.style.color = 'red'
                button.innerHTML = result.count
                
            } else {
                button.classList.remove('bi-heart-fill')
                button.classList.add('bi-heart')
                button.style.color = 'black'
                button.innerHTML = result.count
            }
        }
    </script>


    <!-- comment create -->
    <script> 
    let commentForms = document.querySelectorAll('.comment-Form')
    commentForms.forEach(function(commentForm){    
        commentForm.addEventListener('submit', function(event){
            event.preventDefault()
            const data = new FormData(event.target)
            axios.post(event.target.action, data)
                .then(function(response){
                const comment = response.data
                const commentList = document.querySelector(
                    `#comment-list-${comment.postId}`)
                const newComment = `
                    ${comment.username} : ${comment.content}
                    <i class="bi bi-heart comment_heart" data-post-id="${comment.postId}" data-comment-id="${comment.id}" onclick="comment_likeRequest(this, '${comment.postId}', '${comment.id}')">0명이 좋아합니다.</i>
                    <button class="btn btn-light" onclick="commentDelete('${comment.postId},${comment.id}');">Delete</button>
                </div>`;
                commentList.insertAdjacentHTML('beforeEnd', newComment)
                event.target.reset()
            })
        })
    })
    </script>


    <!-- comment update -->
    <script>
        function commentUpdate(value) {
            var valuesArray = value.split(',')
            var comment_id = valuesArray[1];
            var post_id = valuesArray[0];
            var commentContent = $('.commentContent'+post_id+'-'+comment_id).val();
            // console.log(commentContent, valuesArray)

            $.ajax({
                type: 'POST',
                url: `/posts/${post_id}/comments/${comment_id}/update/`,
                dataType : 'json',
                data: {
                    'comment_id': comment_id,
                    'post_id': post_id,
                    'comment_content': commentContent,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(response) {
                    $('#commentModal').modal('hide');
                    location.reload();
                },
            });
        }
    </script>


    <!-- comment_delete -->
    <script> 
        function commentDelete(value) {
            var valuesArray = value.split(',')
            var comment_id = valuesArray[1];
            var post_id = valuesArray[0];
            $.ajax({
                type : 'POST',
                url : `/posts/${post_id}/comments/${comment_id}/delete/`,
                dataType : 'json',
                data : {
                    'comment_id': comment_id,
                    'post_id': post_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                },
                success: function(response){
                    location.reload()
                }
            })
    }
    </script>


    <!-- comment like  -->
    <script>
    let comment_likeRequest = async (button, postId, commentId) => {
        let likeURL = `/posts/${postId}/comments/${commentId}/likes-async/`;
        try {
            let response = await fetch(likeURL);
            let result = await response.json();

            if (result.status) {
                button.classList.remove('bi-heart', 'comment_heart');
                button.classList.add('bi-heart-fill', 'comment_heart');
                button.style.color = 'red';
            } else {
                button.classList.remove('bi-heart-fill', 'comment_heart');
                button.classList.add('bi-heart', 'comment_heart');
                button.style.color = 'black';
            }

            button.innerHTML = result.count + "명이 좋아합니다.";
        } catch (error) {
            console.error('Error during like request:', error);
        }
    };
      
      
    // reply form toggle
    $('.replybutton').click(function(){
    $(this).next('.replyform_div').toggle();
    });    

    // reply create
    let replyForms = document.querySelectorAll('.reply-Form')
    replyForms.forEach(function(replyForm){
        replyForm.addEventListener('submit', function(event){
            event.preventDefault()
            const data = new FormData(event.target)
            axios.post(event.target.action, data)
                .then(function(response){
                const reply = response.data
                const replyList = document.querySelector(
                    `#reply-list-${reply.postId}-${reply.commentId}`)
                const newReply = `<div class="in">
                            ${ reply.username } : ${ reply.content }
                            <button onclick="replyDelete('${reply.postId},${reply.commentId},${reply.id}');">Delete</button>
                        </div>`
                replyList.insertAdjacentHTML('beforeEnd', newReply)
                event.target.reset()
                })
            })
        })


    // reply_delete
        function replyDelete(value) {
            var valuesArray = value.split(',')
            var reply_id = valuesArray[2];
            var comment_id = valuesArray[1];
            var post_id = valuesArray[0];
            $.ajax({
                type : 'POST',
                url : `/posts/${post_id}/comments/${comment_id}/replys/${reply_id}/delete/`,
                dataType : 'json',
                data : {
                    'reply_id' : reply_id,
                    'comment_id': comment_id,
                    'post_id': post_id,
                    'csrfmiddlewaretoken': '{{csrf_token}}',
                },
                success: function(response){
                    location.reload()
                }
            })
        }

    // reply_update
        function replyUpdate(value) {
            var valuesArray = value.split(',')
            var reply_id = valuesArray[2];
            var comment_id = valuesArray[1];
            var post_id = valuesArray[0];
            var replyContent = $('.replyContent'+post_id+'-'+comment_id+'-'+reply_id).val();
            // console.log(replyContent, valuesArray)

            $.ajax({
                type: 'POST',
                url: `/posts/${post_id}/comments/${comment_id}/replys/${reply_id}/update/`,
                dataType : 'json',
                data: {
                    'reply_id' : reply_id,
                    'comment_id': comment_id,
                    'post_id': post_id,
                    'reply_content': replyContent,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(response) {
                    $('#replyModal').modal('hide');
                    location.reload();
                },
            });
        }
      
    </script>

posts/templates/_commentmodal.html
<div class="modal fade" id="commentModal{{ post.id }}-{{ comment.id }}" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="commentModalLabel">Update</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form>
            <div class="mb-3">
                <p>작성자 : {{ comment.user }}</p>
            </div>
            <div class="mb-3">
                <label for="content" class="col-form-label">Content</label>
                <textarea class="form-control commentContent{{ post.id }}-{{ comment.id }}" id="comment-content">{{ comment.content }}</textarea>
            </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="commentUpdate('{{post.id}},{{comment.id}}')">Update</button>
        </div>
        </div>
    </div>
</div>

posts/templates/_replymodal.html
<div class="modal fade" id="replyModal{{ post.id }}-{{ comment.id }}-{{ reply.id }}" tabindex="-1" aria-labelledby="replyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="replyModalLabel">Update</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form>
            <div class="mb-3">
                <p>작성자 : {{ reply.user }}</p>
            </div>
            <div class="mb-3">
                <label for="content" class="col-form-label">Content</label>
                <textarea class="form-control replyContent{{ post.id }}-{{ comment.id }}-{{ reply.id }}" id="reply-content">{{ reply.content }}</textarea>
            </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="replyUpdate('{{post.id}},{{comment.id}},{{reply.id}}')">Update</button>
        </div>
        </div>
    </div>
</div>

posts/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">

        <!-- <label for="Category-Form" class="form-label">Category</label>
        <select class="form-select" aria-label="Category-Form">
            {% for category in categories %}
            {% if category.id == 1 %}
            <option value="{{category}}" selected>{{category}}</option>
            {% else %}
            <option value="{{category}}">{{category}}</option>
            {% endif %}
            {% endfor %}
        </select>

        <div class="mb-3">
            <label for="Title-Form" class="form-label">Title</label>
            <input type="text" class="form-control" id="Title-Form" placeholder="Title">
          </div>
          <div class="mb-3">
            <label for="Content-Form" class="form-label">Content</label>
            <textarea class="form-control" id="Content-Form" rows="5" placeholder="Content"></textarea>
        </div>

        <div class="mb-3">
            <label class="Image-Form" for="inputGroupFile02">image</label>
            <input type="file" class="form-control" id="Image-Form">
        </div>

        <input type="submit"> -->
    </form>
{% endblock %}