GUCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/likes-async/', views.likes_async, name='likes-async'),

    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/update/', views.comment_update, name='comment_update'),
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/comments/<int:id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<int:post_id>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/delete/', views.reply_delete, name='reply_delete'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/update/', views.reply_update, name='reply_update'),

    path('catemp/', views.catemp, name='catempPage'),
    path('catemp/create', views.Create_catemp, name='catempCreate'),
    path('catemp/update', views.Update_catemp, name='catempUpdate'),
    path('catemp/delete', views.Delete_catemp, name='catempDelete'),

    path('<str:username>/followsHome/', views.followsHome, name='followsHome'),
    path('<int:id>/<str:username>/followsDetail/', views.followsDetail, name='followsDetail'),

]

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)

class Post(models.Model):

    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default='1')
    TAG_CHOICES = [
        ('RESTAURANT', '맛집'),
        ('HOBBY', '취미'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = ResizedImageField(
        size = [500, 500],
        crop = ['middle', 'center'],
        upload_to = 'image/%Y/%m',
    )
    tag = models.CharField(max_length=30, choices = TAG_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Reply(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post', 'user', 'like_users', )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': '3',
                    'placeholder': '댓글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ('user', 'post', 'comment',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control mt-2',
                    'rows': '3',
                    'placeholder': '답글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }
        

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from accounts.models import User
from .forms import PostForm, CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts': posts,
    }

    return render(request, 'blogHome/base.html', context)

def detail(request, id):
    post = Post.objects.get(id=id)
    sorted_posts = post.user.post_set.all().order_by('-created_at')
    comment_form = CommentForm()
    reply_form = ReplyForm()
    categories = Category.objects.all()

    context = {
        'post':post,
        'sorted_posts':sorted_posts,
        'comment_form':comment_form,
        'reply_form':reply_form,
        'categories':categories,
    }
    return render(request, 'blogDetail/base.html', context)

def catemp(request):
    categories = Category.objects.all()
    if not categories:
        categories = Category()
        categories.category_name = '기본 카테고리'
        categories.save()

    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catemp.html', context)

@login_required
def Create_catemp(request):
    category_name = request.POST['categoryName']
    new_category = Category(category_name = category_name)
    new_category.save()

    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def Update_catemp(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catempUpdate.html', context)

@login_required
def Delete_catemp(request):
    category_id = request.POST['categoryId']
    delete_category = Category.objects.get(id = category_id)
    delete_category.delete()
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    else:
        form = PostForm()
        
    context = {
        'form': form, 
        'categories':categories,
    }

    return render(request, 'form.html', context)


@login_required
def delete(request, id):
    post = Post.objects.get(id=id)
    if request.user == post.user:
        post.delete()

    return redirect('posts:home')


@login_required
def update(request, id):
    post = Post.objects.get(id=id)

    if request.user != post.user:
        return redirect('posts:detail')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', id=post.id)
    
    else:
        form = PostForm(instance=post)

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    
    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()

    return JsonResponse({
                            'id': comment.id,
                            'postId': post_id,
                            'username': comment.user.username,
                            'content': comment.content,
    })


@login_required
def comment_update(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    if request.method == 'POST':
        comment.content = request.POST.get('comment_content')
        comment.save()
        data = {
        'comment_id': id,
        'post_id': post_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    else:
        comment.delete()
        data = {
            'post_id': post_id,
            'comment_id' : id,
        }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')



@login_required
def likes_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False

    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all()),
    }

    return JsonResponse(context)



@login_required
def comment_likes_async(request, post_id, id):
    user = request.user
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=id)

    if user in comment.like_users.all():
        comment.like_users.remove(user)
        status = False

    else:
        comment.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(comment.like_users.all()),
        'post_id': post.id,
        'comment_id': comment.id,
    }
    return JsonResponse(context)


@login_required
def reply_create(request, post_id, comment_id):
    reply_form = ReplyForm(request.POST)
    if reply_form.is_valid():
        reply = reply_form.save(commit=False)
        reply.post_id = post_id
        reply.user = request.user
        reply.comment_id = comment_id
        reply.save() 

    return JsonResponse({
                            'id': reply.id,
                            'postId': post_id,
                            'commentId': comment_id,
                            'username': reply.user.username,
                            'content': reply.content,
    })


@login_required
def reply_delete(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')
    
    else:
        reply.delete()
        data = {
            'reply_id': id,
            'post_id': post_id,
            'comment_id' : comment_id,
        }
    
    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def reply_update(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')

    if request.method == 'POST':
        reply.content = request.POST.get('reply_content')
        reply.save()
        data = {
        'reply_id': id,
        'post_id': post_id,
        'comment_id' : comment_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def followsHome(request, username):
    me = request.user
    you = User.objects.get(username=username)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)
    
    return redirect('posts:home')


@login_required
def followsDetail(request, username, id):
    me = request.user
    you = User.objects.get(username=username)
    post = Post.objects.get(id=id)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)

    context = {
        'post': post,
    }

    return redirect('posts:detail', id=post.id)

posts/templates/blogHome/__allPosts.html
<div id='allPosts' class="m-2 rounded-2 d-flex" style="flex-direction: column;">
    {% for post in posts %}
        {% if post.user.profile_image %}
            <div class="d-flex align-items-center" style="width: 100%;">
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
        {% else %}
            <div class="d-flex align-items-center" style="width: 100%;">
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
        {% endif %}
            <div>
                <p class="m-0" style="font-size: 0.75rem;">{{ post.user }}</p>
                <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
            </div>
                {% if user != post.user and user.is_authenticated %}
                <div class="col-4">
                    {% if user in post.user.followers.all %}
                        <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                    {% else %}
                        <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                    {% endif %}
                </div>
                {% endif %}
            <!-- <button type="button" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</button> -->
        </div>
        <a href="{% url 'posts:detail' id=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
            <h5 class="fw-bold mt-1">{{ post.title }}</h5>
            <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                {{ post.content}}
            </p>
        </a>
        <hr class="mt-0">
    {% endfor %}
</div>

posts/templates/blogHome/__allRestaurants.html
<div id='allRestaurants' class="m-2 rounded-2 d-flex" style="flex-direction: column;">
    {% for post in posts %}
        {% if post.tag == 'RESTAURANT' %}
            {% if post.user.profile_image %}
                <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
            {% else %}
                <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
            {% endif %}
                <div>
                    <p class="m-0" style="font-size: 0.75rem;">{{ post.user }}</p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
                </div>
                    {% if user != post.user and user.is_authenticated %}
                    <div class="col-4">
                        {% if user in post.user.followers.all %}
                            <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                        {% else %}
                            <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                        {% endif %}
                    </div>
                    {% endif %}
                <!-- <button type="button" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</button> -->
            </div>
            <a href="{% url 'posts:detail' id=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                <h5 class="fw-bold mt-1">{{ post.title }}</h5>
                <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                    {{ post.content}}
                </p>
            </a>
            <hr class="mt-0">
        {% endif %}
    {% endfor %}
</div>

posts/templates/blogHome/__allhobbies.html
<div id='allRestaurants' class="m-2 rounded-2 d-flex" style="flex-direction: column;">
    {% for post in posts %}
        {% if post.tag == 'HOBBY' %}
            {% if post.user.profile_image %}
                <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
            {% else %}
                <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
            {% endif %}
                <div>
                    <p class="m-0" style="font-size: 0.75rem;">{{ post.user }}</p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
                </div>
                    {% if user != post.user and user.is_authenticated %}
                    <div class="col-4">
                        {% if user in post.user.followers.all %}
                            <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                        {% else %}
                            <a href="{% url 'posts:followsHome' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                        {% endif %}
                    </div>
                    {% endif %}
                <!-- <button type="button" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</button> -->
            </div>
            <a href="{% url 'posts:detail' id=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                <h5 class="fw-bold mt-1">{{ post.title }}</h5>
                <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                    {{ post.content}}
                </p>
            </a>
            <hr class="mt-0">
        {% endif %}
    {% endfor %}
</div>

posts/templates/blogHome/_allUserPost.html
<article class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid black; flex-direction: column;">
    <div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#" onclick="showContent('allPosts')">전체</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onclick="showContent('allRestaurants')">맛집</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onclick="showContent('allhobbies')">취미</a>
            </li>
        </ul>
    </div>


    <div id="allPostsContent" class="content">
      {% include 'blogHome/__allPosts.html' %}
    </div>

    <div id="allRestaurantsContent" class="content" style="display: none;">
        {% include 'blogHome/__allRestaurants.html' %}

    </div>

    <div id="allhobbiesContent" class="content" style="display: none;">
      {% include 'blogHome/__allhobbies.html' %}
  </div>
    
    <nav class="mt-auto">
        <ul class="pagination justify-content-center">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
    </nav>
</article>


{% include 'blogHome/_allUserPost_js.html' %}

posts/templates/blogHome/_allUserPost_js.html
<script>
    $(document).ready(function(){
        $(".nav-link").click(function(){
            event.preventDefault(); // 새로고침 방지

            $(".nav-link").removeClass("active");
            $(this).addClass("active");
        });
    });

    function showContent(contentId) {
        // 모든 content를 숨김
        document.querySelectorAll('.content').forEach(function(element) {
            element.style.display = 'none';
        });

        // 클릭한 탭에 해당하는 content를 보이게 함
        document.getElementById(contentId + 'Content').style.display = 'block';
    }

</script>

posts/templates/blogHome/_login.html
<div class="m-2 rounded-2 d-flex" style="border: 2px solid rgb(0, 0, 0); flex-direction: column;">
    <div class="d-flex align-items-center" style="width: 100%;">
        {% if user.profile_image %}
            <div class="m-1" style="width: 50px; height: 50px; border-radius: 70%; overflow: hidden;">
                <img src="{{ user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
            </div>
        {% else %}
            <div class="m-1" style="width: 50px; height: 50px; border-radius: 70%; overflow: hidden;">
                <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
            </div>
        {% endif %}
        <div>
            <p style="font-size: 0.75rem;">{{ user.username }}</p>
        </div>
        <button onclick="location.href='/accounts/logout/'" type="button" class="btn btn-secondary ms-auto me-1" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">로그아웃</button>
    </div>
        <div class="btn-group mt-2" role="group" aria-label="Basic example">
            <button onclick="location.href='/accounts/<str:username>/'" type="button" class="btn btn-primary">내블로그</button>
        <button onclick="location.href='/posts/create/'" type="button" class="btn btn-primary">글쓰기</button>
    </div>
</div>

posts/templates/blogHome/_logout.html
<div class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid rgb(0, 0, 0); flex-direction: column;">
    <button onclick="location.href='/accounts/login/'" type="button" class="btn btn-primary my-1">
        로그인
    </button>
    <button onclick="location.href='/accounts/signup/'" type="button" class="btn btn-primary my-1">
        회원가입
    </button>
</div>

posts/templates/blogHome/_myList.html
<div class="m-2 p-1 rounded-2" style="border: 2px solid rgb(0, 0, 0);">
    <div class="d-flex justify-content-around">
        <button type="button" class="btn btn-outline-dark my-1">
            버튼1
        </button>
        <button type="button" class="btn btn-outline-dark my-1">
            버튼2
        </button>
    </div>
    <p></p>
</div>

posts/templates/blogHome/_neighborPost.html
<article class="m-2 rounded-2" style="border: 2px solid black;">
                
    <div class="m-2 rounded-2 d-flex" style="flex-direction: column;">
        <h4>내 이웃의 글</h4>
        {% if user.is_authenticated %}
          {% if request.user.followings.all|length == 0 %}
            이웃을 추가해보세요!
          {% else %}
            {% for following_user in request.user.followings.all %}
              {% for post in following_user.post_set.all %}
                <hr class="mt-1">
                  <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                          {% if post.user.profile_image %}
                          <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                          {% else %}
                          <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                          {% endif %}
                      </div>
                      <div>
                          <p style="font-size: 0.75rem;">{{ post.user }}</p>
                      </div>
                  </div>
                  <h5 class="fw-bold mt-1">{{ post.title }}</h5> 
                  <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2;">
                    {{ post.content}}        
                  </p>
                <hr class="mt-0">
              {% endfor %}
            {% endfor %}
          {% endif %}
        {% else %}
         로그인이 필요합니다.
        {% endif %}



    </div>

    <nav class="mt-auto">
        <ul class="pagination justify-content-center">
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
    </nav>
</article>

posts/templates/blogHome/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>블로그 홈</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

</head>
    <body>
    {% include '_nav.html' %}
    
    <div class="container-lg">
        <section class="float-start" style="width: 100%; margin-right: -250px; padding-right: 250px;">
            {% include 'blogHome/_neighborPost.html' %}
            {% include 'blogHome/_allUserPost.html' %}
        </section>

        <aside class="float-end" style="width: 240px;">
            {% if user.is_authenticated %}
                {% include 'blogHome/_login.html' %}
            {% else %}
                {% include 'blogHome/_logout.html' %}
            {% endif %}
                {% include 'blogHome/_myList.html' %}
        </aside>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>