GUCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/likes-async/', views.likes_async, name='likes-async'),

    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/update/', views.comment_update, name='comment_update'),
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/comments/<int:id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<int:post_id>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/delete/', views.reply_delete, name='reply_delete'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/update/', views.reply_update, name='reply_update'),

    path('catemp/', views.catemp, name='catempPage'),
    path('catemp/create', views.Create_catemp, name='catempCreate'),
    path('catemp/update', views.Update_catemp, name='catempUpdate'),
    path('catemp/delete', views.Delete_catemp, name='catempDelete'),

    path('<str:username>/followsHome/', views.followsHome, name='followsHome'),
    path('<int:id>/<str:username>/followsDetail/', views.followsDetail, name='followsDetail'),

]

posts/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)

class Post(models.Model):

    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default='1')
    TAG_CHOICES = [
        ('RESTAURANT', '맛집'),
        ('HOBBY', '취미'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = ResizedImageField(
        size = [500, 500],
        crop = ['middle', 'center'],
        upload_to = 'image/%Y/%m',
    )
    tag = models.CharField(max_length=30, choices = TAG_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Reply(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users', )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post', 'user', 'like_users', )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': '3',
                    'placeholder': '댓글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ('user', 'post', 'comment',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control mt-2',
                    'rows': '3',
                    'placeholder': '답글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }
        

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import *
from accounts.models import User
from .forms import PostForm, CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder

# Create your views here.

def home(request):
    posts = Post.objects.all().order_by('-id')

    context = {
        'posts': posts,
    }

    return render(request, 'blogHome/base.html', context)

def detail(request, id):
    post = Post.objects.get(id=id)
    sorted_posts = post.user.post_set.all().order_by('-created_at')
    comment_form = CommentForm()
    reply_form = ReplyForm()
    categories = Category.objects.all()

    context = {
        'post':post,
        'sorted_posts':sorted_posts,
        'comment_form':comment_form,
        'reply_form':reply_form,
        'categories':categories,
    }
    return render(request, 'blogDetail/base.html', context)

def catemp(request):
    categories = Category.objects.all()
    if not categories:
        categories = Category()
        categories.category_name = '기본 카테고리'
        categories.save()

    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catemp.html', context)

@login_required
def Create_catemp(request):
    category_name = request.POST['categoryName']
    new_category = Category(category_name = category_name)
    new_category.save()

    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def Update_catemp(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'blogDetail/catempUpdate.html', context)

@login_required
def Delete_catemp(request):
    category_id = request.POST['categoryId']
    delete_category = Category.objects.get(id = category_id)
    delete_category.delete()
    return HttpResponseRedirect(reverse('posts:catempPage'))

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    else:
        form = PostForm()
        
    context = {
        'form': form, 
        'categories':categories,
    }

    return render(request, 'form.html', context)


@login_required
def delete(request, id):
    post = Post.objects.get(id=id)
    if request.user == post.user:
        post.delete()

    return redirect('posts:home')


@login_required
def update(request, id):
    post = Post.objects.get(id=id)

    if request.user != post.user:
        return redirect('posts:detail')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', id=post.id)
    
    else:
        form = PostForm(instance=post)

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:home')
    
    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, post_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()

    return JsonResponse({
                            'id': comment.id,
                            'postId': post_id,
                            'username': comment.user.username,
                            'content': comment.content,
    })


@login_required
def comment_update(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    if request.method == 'POST':
        comment.content = request.POST.get('comment_content')
        comment.save()
        data = {
        'comment_id': id,
        'post_id': post_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def comment_delete(request, post_id, id):
    comment = Comment.objects.get(id=id)

    if request.user != comment.user:
        return redirect('posts:home')
    
    else:
        comment.delete()
        data = {
            'post_id': post_id,
            'comment_id' : id,
        }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')



@login_required
def likes_async(request, id):
    user = request.user
    post = Post.objects.get(id=id)

    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False

    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all()),
    }

    return JsonResponse(context)



@login_required
def comment_likes_async(request, post_id, id):
    user = request.user
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=id)

    if user in comment.like_users.all():
        comment.like_users.remove(user)
        status = False

    else:
        comment.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(comment.like_users.all()),
        'post_id': post.id,
        'comment_id': comment.id,
    }
    return JsonResponse(context)


@login_required
def reply_create(request, post_id, comment_id):
    reply_form = ReplyForm(request.POST)
    if reply_form.is_valid():
        reply = reply_form.save(commit=False)
        reply.post_id = post_id
        reply.user = request.user
        reply.comment_id = comment_id
        reply.save() 

    return JsonResponse({
                            'id': reply.id,
                            'postId': post_id,
                            'commentId': comment_id,
                            'username': reply.user.username,
                            'content': reply.content,
    })


@login_required
def reply_delete(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')
    
    else:
        reply.delete()
        data = {
            'reply_id': id,
            'post_id': post_id,
            'comment_id' : comment_id,
        }
    
    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def reply_update(request, post_id, comment_id, id):
    reply = Reply.objects.get(id=id)

    if request.user != reply.user:
        return redirect('posts:home')

    if request.method == 'POST':
        reply.content = request.POST.get('reply_content')
        reply.save()
        data = {
        'reply_id': id,
        'post_id': post_id,
        'comment_id' : comment_id,
    }

    return HttpResponse(json.dumps(data, cls=DjangoJSONEncoder), content_type = 'application/json')


@login_required
def followsHome(request, username):
    me = request.user
    you = User.objects.get(username=username)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)
    
    return redirect('posts:home')


@login_required
def followsDetail(request, username, id):
    me = request.user
    you = User.objects.get(username=username)
    post = Post.objects.get(id=id)

    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)

    context = {
        'post': post,
    }

    return redirect('posts:detail', id=post.id)

posts/templates/blogDetail/__comment&reply.html
<div class="m-2">
    <p class="d-inline-flex gap-1">
        <div class="btn-group" role="group" aria-label="">
            <button class="btn btn-outline-primary" data-bs-toggle="collapse" href="#likeUsers" role="button" aria-expanded="false">
                공감
            </button>
            <button type="button" class="btn btn-outline-primary">
                {% if user in post.like_users.all %}
                    <i class="bi bi-heart-fill heart align-self-center" style="color:red; font-size: 1rem;" data-post-id="{{ post.id }}">{{ post.like_users.all|length }} </i>
                {% else %}
                    <i class="bi bi-heart heart align-self-center" style="font-size: 1rem;" data-post-id="{{ post.id }}">{{ post.like_users.all|length }} </i>
                {% endif %}
            </button>
        </div>
        <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#comment" aria-expanded="false" aria-controls="comment">
          댓글
        </button>
      </p>

      <div class="collapse" id="comment">
        <hr>
        {% for comment in post.comment_set.all %}

        <!-- comment -->
        <div class="d-flex align-items-center" style="width: 100%;">
            {% if comment.user.profile_image %}
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ comment.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
            {% else %}
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
            {% endif %}
            <div class="mx-2">
                <p class="m-0" style="font-size: 1rem;">{{ comment.user }}</p>
                <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ comment.updated_at }}</p>
            </div>
            <div class="ms-auto my-0 py-0">
                <div class="ms-auto">
                    {% if user == comment.user %}
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                            <ul class="dropdown-menu">
                                <li><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#commentModal{{ post.id }}-{{ comment.id }}">수정하기</button></li>
                                <li><button onclick="commentDelete('{{post.id}},{{comment.id}}');" class="dropdown-item" href="#">삭제하기</button></li>
                            </ul>
                        </div>
                        {% include '_commentmodal.html' %}
                    {% else %}
                        <div class="dropdown">
                            <button class="btn dropdown-toggle" type="button" style="visibility: hidden;"></button>
                        </div>
                    {% endif %}
                </div>
                <div class="my-0 py-0 me-2">
                    {% if user in comment.like_users.all %}
                        <i class="bi bi-heart-fill comment_heart align-self-center " style="color:red; font-size: 1rem;" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" onclick="comment_likeRequest(this, '{{ post.id }}', '{{ comment.id }}')">{{ comment.like_users.all|length }}</i> 
                    {% else %}
                        <i class="bi bi-heart comment_heart align-self-center" style="font-size: 1rem;" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" onclick="comment_likeRequest(this, '{{ post.id }}', '{{ comment.id }}')">{{ comment.like_users.all|length }}</i>                
                    {% endif %}
                </div>
            </div>
        </div>
        
        <p class="mt-2 ms-1">{{ comment.content }}</p>
        <div class="d-flex align-items-center" style="width: 100%;">
            <button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#reply-list-{{ post.id }}-{{ comment.id }}" aria-expanded="false" aria-controls="reply" style="--bs-btn-padding-y: 0rem; --bs-btn-padding-x: .3rem; --bs-btn-font-size: .75rem;">답글</button>
        </div>

        <div class="collapse" id="reply-list-{{ post.id }}-{{ comment.id }}">
            {% if user.is_authenticated %}
            <form action="{% url 'posts:reply_create' post_id=post.id comment_id=comment.id %}" method="POST" class="reply-Form">
                {% csrf_token %}
                {{ reply_form }}
                <div class="mt-3 d-flex">
                    <input type="submit" class="ms-auto btn btn-secondary" value="답글 작성">
                </div>
            </form>
            {% endif %}
        </div>
        
        <!-- reply -->
        <div class="ms-2">
            {% for reply in comment.reply_set.all %}
            <div class="d-flex align-items-center" style="width: 100%;">
                
                {% if reply.user.profile_image %}
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="{{ reply.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
                {% else %}
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
                {% endif %}
                <div>
                    <p class="m-0" style="font-size: 1rem;">{{ reply.user }}</p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ reply.updated_at }}</p>
                </div>
                {% if user == reply.user %}
                    <div class="dropdown ms-auto">
                        <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu">
                            <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#replyModal{{ post.id }}-{{ comment.id }}-{{ reply.id }}">수정하기</button></li>
                            <li><button onclick="replyDelete('{{post.id}},{{comment.id}},{{reply.id}}');" class="dropdown-item" href="#">삭제하기</button></li>
                        </ul>
                    </div>
                {% include '_replymodal.html' %}
                {% endif %}

            </div>
            <p class="ms-3">{{ reply.content }}</p>
            {% endfor %}
        </div>
        <hr>
        {% endfor %}

        {% if user.is_authenticated %}
        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST" class="comment-Form">
            {% csrf_token %}
            {{ comment_form }}
            <div class="mt-3 d-flex">
                <input type="submit" class="ms-auto btn btn-secondary" value="댓글 작성">
            </div>
        </form>
        {% endif %}
      </div>

      <div class="collapse" id="likeUsers">
        <div class="overflow-auto">
            <div class="bg-warning d-flex m-1 float-start" style="height: 30px; width: 200px;">
                <div style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fdi0GrI%2FbtqyyWdEYM8%2FLbDOJG6QuYVXzFI9AlMq60%2Fimg.png" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div class="mx-1">
                    <p style="font-size: 0.75rem;">아이디</p>
                </div>
                <button type="button" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</button>
            </div>
        </div>
      </div>
</div>

{% include 'blogDetail/__comment&reply_js.html' %}

posts/templates/blogDetail/__comment&reply_js.html
<!-- post like -->
<script>
    let likeButtons = document.querySelectorAll("i.heart")

    likeButtons.forEach((likeButton)=>{            
        likeButton.addEventListener("click", (event)=>{
            let postId = event.target.dataset.postId 
            likeRequest(event.target, postId)
        })
    })

    let likeRequest = async (button, postId) => {
        let likeURL = `/posts/${postId}/likes-async/`
        let response = await fetch(likeURL)
        let result = await response.json()

        if (result.status) {
            button.classList.remove('bi-heart')
            button.classList.add('bi-heart-fill')
            button.style.color = 'red'
            
        } else {
            button.classList.remove('bi-heart-fill')
            button.classList.add('bi-heart')
            button.style.color = 'black'
        }
    button.innerHTML = result.count;
    }



// comment create
let commentForms = document.querySelectorAll('.comment-Form')
commentForms.forEach(function(commentForm){    
    commentForm.addEventListener('submit', function(event){
        event.preventDefault()
        const data = new FormData(event.target)
        axios.post(event.target.action, data)
            .then(function(response){
            const comment = response.data
            const commentList = document.querySelector(
                `#comment-list-${comment.postId}`)
            const newComment = `
                ${comment.username} : ${comment.content}
                <i class="bi bi-heart comment_heart" data-post-id="${comment.postId}" data-comment-id="${comment.id}" onclick="comment_likeRequest(this, '${comment.postId}', '${comment.id}')">0명이 좋아합니다.</i>
                <button class="btn btn-light" onclick="commentDelete('${comment.postId},${comment.id}');">Delete</button>
            </div>`;
            commentList.insertAdjacentHTML('beforeEnd', newComment)
            event.target.reset()
        })
    })
})


// comment update
function commentUpdate(value) {
    var valuesArray = value.split(',')
    var comment_id = valuesArray[1];
    var post_id = valuesArray[0];
    var commentContent = $('.commentContent'+post_id+'-'+comment_id).val();
    // console.log(commentContent, valuesArray)

    $.ajax({
        type: 'POST',
        url: `/posts/${post_id}/comments/${comment_id}/update/`,
        dataType : 'json',
        data: {
            'comment_id': comment_id,
            'post_id': post_id,
            'comment_content': commentContent,
            'csrfmiddlewaretoken': '{{ csrf_token }}',
        },
        success: function(response) {
            $('#commentModal').modal('hide');
            location.reload();
        },
    });
}



// comment_delete
function commentDelete(value) {
    var valuesArray = value.split(',')
    var comment_id = valuesArray[1];
    var post_id = valuesArray[0];
    $.ajax({
        type : 'POST',
        url : `/posts/${post_id}/comments/${comment_id}/delete/`,
        dataType : 'json',
        data : {
            'comment_id': comment_id,
            'post_id': post_id,
            'csrfmiddlewaretoken': '{{csrf_token}}',
        },
        success: function(response){
            location.reload()
        }
    })
}



// comment like 
let comment_likeRequest = async (button, postId, commentId) => {
    let likeURL = `/posts/${postId}/comments/${commentId}/likes-async/`;
    try {
        let response = await fetch(likeURL);
        let result = await response.json();

        if (result.status) {
            button.classList.remove('bi-heart', 'comment_heart');
            button.classList.add('bi-heart-fill', 'comment_heart');
            button.style.color = 'red';
        } else {
            button.classList.remove('bi-heart-fill', 'comment_heart');
            button.classList.add('bi-heart', 'comment_heart');
            button.style.color = 'black';
        }

        button.innerHTML = result.count;
    } catch (error) {
        console.error('Error during like request:', error);
    }
};
    
    
// reply form toggle
$('.replybutton').click(function(){
$(this).next('.replyform_div').toggle();
});    

// reply create
let replyForms = document.querySelectorAll('.reply-Form')
replyForms.forEach(function(replyForm){
    replyForm.addEventListener('submit', function(event){
        event.preventDefault()
        const data = new FormData(event.target)
        axios.post(event.target.action, data)
            .then(function(response){
            const reply = response.data
            const replyList = document.querySelector(
                `#reply-list-${reply.postId}-${reply.commentId}`)
            const newReply = `<div class="in">
                        ${ reply.username } : ${ reply.content }
                        <button onclick="replyDelete('${reply.postId},${reply.commentId},${reply.id}');">Delete</button>
                    </div>`
            replyList.insertAdjacentHTML('beforeEnd', newReply)
            event.target.reset()
            })
        })
    })


// reply_delete
    function replyDelete(value) {
        var valuesArray = value.split(',')
        var reply_id = valuesArray[2];
        var comment_id = valuesArray[1];
        var post_id = valuesArray[0];
        $.ajax({
            type : 'POST',
            url : `/posts/${post_id}/comments/${comment_id}/replys/${reply_id}/delete/`,
            dataType : 'json',
            data : {
                'reply_id' : reply_id,
                'comment_id': comment_id,
                'post_id': post_id,
                'csrfmiddlewaretoken': '{{csrf_token}}',
            },
            success: function(response){
                location.reload()
            }
        })
    }

// reply_update
    function replyUpdate(value) {
        var valuesArray = value.split(',')
        var reply_id = valuesArray[2];
        var comment_id = valuesArray[1];
        var post_id = valuesArray[0];
        var replyContent = $('.replyContent'+post_id+'-'+comment_id+'-'+reply_id).val();
        // console.log(replyContent, valuesArray)

        $.ajax({
            type: 'POST',
            url: `/posts/${post_id}/comments/${comment_id}/replys/${reply_id}/update/`,
            dataType : 'json',
            data: {
                'reply_id' : reply_id,
                'comment_id': comment_id,
                'post_id': post_id,
                'reply_content': replyContent,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            success: function(response) {
                $('#replyModal').modal('hide');
                location.reload();
            },
        });
    }
    
</script>

posts/templates/blogDetail/_category.html
<div class="m-2 p-1 rounded-2" style="border: 2px solid rgb(0, 0, 0); height: 30rem;">
    <div class="d-flex justify-content-between align-items-center">
        <p class="ms-1 mb-0 fs-6 fw-bold">카테고리 리스트</p>
        <a onclick="location.href='/posts/catemp/'" class="btn btn-secondary me-1" style="--bs-btn-padding-y: .1rem; --bs-btn-padding-x: .2rem; --bs-btn-font-size: 0.75rem;">관리</a>
    </div>
    {% for category in categories %}
        <div>
            <a href="#" class="ms-3 my-0 mt-1 link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">{{category.category_name}}</a>
        </div>
    {% endfor %}

</div>

posts/templates/blogDetail/_nowpost.html
<article class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid black; flex-direction: column;">
    <div class="m-2 rounded-2 d-flex" style="flex-direction: column;">
        <div class="d-flex justify-content-between">
            <h4 class="fw-bold mt-1">{{ post.title }}</h4>
            {% if user == post.user %}
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'posts:update' id=post.id %}">수정하기</a></li>
                    <li><a class="dropdown-item" href="{% url 'posts:delete' id=post.id %}">삭제하기</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
        <div class="d-flex align-items-center" style="width: 100%;">
            {% if post.user.profile_image %}
            <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            {% else %}
            <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                <img src="/media/profile/default.jpeg" alt="" style="width: 100%; height: 100%; object-fit: cover;">
            </div>
            {% endif %}
            <div class="mx-2">
                <p class="m-0" style="font-size: 1rem;">{{ post.user }}</p>
                <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
            </div>
            {% if user != post.user and user.is_authenticated %}
                {% if user in post.user.followers.all %}
                    <a href="{% url 'posts:followsDetail' username=post.user.username id=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                {% else %}
                    <a href="{% url 'posts:followsDetail' username=post.user.username id=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                {% endif %}
            {% endif %}
        </div>
        <hr>
        <img src="{{ post.image.url }}" alt="">
        <p> {{ post.content }}</p>
        <hr class="mt-0">
    </div>
    
    {% include 'blogDetail/__comment&reply.html' %}
</article>