GUCo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/likes-async/', views.likes_async, name='likes-async'),

    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:id>/update/', views.comment_update, name='comment_update'),
    path('<int:post_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:post_id>/comments/<int:id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<int:post_id>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/delete/', views.reply_delete, name='reply_delete'),
    path('<int:post_id>/comments/<int:comment_id>/replys/<int:id>/update/', views.reply_update, name='reply_update'),

    path('catemp/', views.catemp, name='catempPage'),
    path('catemp/create', views.Create_catemp, name='catempCreate'),
    path('catemp/update', views.Update_catemp, name='catempUpdate'),
    path('catemp/delete', views.Delete_catemp, name='catempDelete'),

    path('<str:username>/followsHome/', views.followsHome, name='followsHome'),
    path('<int:id>/<str:username>/followsDetail/', views.followsDetail, name='followsDetail'),

]

templates/_nav.html
<!-- 네비게이션, 반응형 -->
<nav class="navbar navbar-expand-sm bg-body-tertiary">
    <!-- 공간을 가득 채움 -->
    <div class="container-fluid">
        <!-- Home 을 가기 위한 링크 -->
        <a class="navbar-brand" href="{% url 'posts:home' %}">Home</a>
        <!-- 링크를 들어가는 버튼 -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <!-- 아이콘 -->
        <span class="navbar-toggler-icon"></span>
        </button>
        <!-- 콜랩스 -->
        <div class="collapse navbar-collapse" id="navbarNav">
        <!-- 네비게이션 -->
        <ul class="navbar-nav">
            <!-- 네비 내용 목록 -->
            <li class="nav-item"><a class="nav-link" href="#">blog</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">로그인</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a></li>
        </ul>
        </div>
    </div>
</nav> 

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
    <body>
    {% include '_nav.html' %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

templates/blogHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">My blog</a>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid mt-2 mx-2 d-flex" style="height: 60em;">
        <div class="bg-primary d-flex" style="flex: 1; flex-direction: column;">
            <div class="bg-warning m-2" style="flex: 3;">
                이웃의 글 리스트
            </div>
            <div class="bg-info m-2 align" style="flex: 7;">
                <div>
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="#">전체</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">태그1</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">태그2</a>
                        </li>
                    </ul>
                </div>
                <div>
                    모든 이용자의 글 리스트
                </div>
            </div>
        </div>
        <div class="bg-danger d-flex" style="width: 15em; flex-direction: column;">
            <div class="bg-warning m-2" style="height: 7em;">프로필</div>
            <button type="button" class="btn btn-primary m-2">게시글 작성 버튼</button>    
            <div class="bg-white m-2" style="flex: 1;">
                <div class="d-grid gap-2 d-flex m-2 justify-content-around">
                    <button class="btn btn-primary" type="button">Button</button>
                    <button class="btn btn-primary" type="button">Button</button>
                </div>
            </div>
        </div>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

templates/blogMain.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">My blog</a>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid mt-2 mx-2 d-flex" style="height: 60em;">
        <div class="bg-warning d-flex" style="width: 15em; flex-direction: column;">
            <div class="bg-secondary m-2" style="height: 10em;">프로필</div>
            <button type="button" class="btn btn-primary m-2">게시글 작성 버튼</button>
            <div class="bg-success m-2" style="flex: 1;;">카테고리</div>
        </div>
        <div class="bg-danger d-flex" style="flex: 1; flex-direction: column;">
            <div class="bg-info m-2" style="flex: 3;">현재 카테고리 내의 글</div>
            <div class="bg-white m-2" style="flex: 7;"> 현재 글</div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

templates/blogPost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="#">My blog</a>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid m-2 d-flex justify-content-between bg-danger">
        <div>
            첨부
        </div>
        <button type="button" class="btn btn-primary m-2">게시글 작성 버튼</button>
    </div>

    <div class="container-fluid m-2 d-flex bg-primary" style="flex: 1; height: 60em;">
        게시글 작업 공간
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>